---
- hosts: deploy
  vars:
  sudo: yes
  roles:
    - { role: common, tags: "common" }
    - { role: ftpd, tags: "ftpd" }
    - { role: nfs, tags: "nfs" }
    - { role: webserver, tags: "webserver" }
